### ISSUE TITLE
NKK_LCD_SWITCH - nodejs - javascript

### ISSUE THREAD

**Issue by yboujraf** [antimodular/nkk_lcd_smartswitch#1]
Dear @antimodular 

I am using raspberry with raspian OS and use nodejs with javascript.

I have some NKK smartswitch like your refeerence and I don't know if you could route me to a link or help us to convert it into javascript.

I have seen many library in C but never found the definition file .h from smartswitch even at nkk website support.

Most have draw line, rectangle, circle, pixels but not her

Thanks in advance if you could help me
Best wishes for 2020
Best Regards
Youssef

**Comment by antimodular** [comment]
Hello Youssef.

We have used the NKK's for this project:
http://lozano-hemmer.com/artworks/nineteen_eighty-four.php 
You can see in the video that we used the switches to display images, that are read in via a USB connection from a host computer.

I do not use their .h or seen it.
Via SPI i sent the received serial data to the NKKs using a teensy 3.2 https://www.pjrc.com/store/teensy32.html.

I hope this helps a bit.

**Comment by yboujraf** [comment]
Dear @antimodular 

I have seen your code and it will help me to manage the Bitmap mapping for RGBin two bytes instead of three.

Question regarding : IS-CHPMP DC/DC voltage step-up converter

https://www.nkkswitches.com/pdf/IS-CHPMP_IS-CHPMPHP_Manual.pdf 

Is it enough to manage 17 buttons or needs more IS-CHPMP DC/DC ?. In your schematic I have seen 9 buttons.

Best whises for 2020,
Youssef

**Comment by antimodular** [comment]
In case you still need the SPI info.
This project is based on Arduino but uses a Teensy micro controller.
Read on how to install it all here: https://www.pjrc.com/teensy/td_download.html
It installs many libraries including SPI.

I had to use 2 step-up converters for my 12 buttons because i noticed one did not deliver enough ampere.

good luck

**Comment by yboujraf** [comment]
Dear @antimodular 

Thanks for the feedback.

Actually I am working with raspberry pi 4 with raspian - nodejs and javascript.
I found the correct lib https://github.com/fivdi/spi-device/issues/12
And tried to make a correct schematic for pins and be sure the power supply because 3.3V for raspberry will not affect the button or vice-versa.

Now I need to write the code with the correct sequence to start the button then will see how to generate the bitmap. As understood I need to send LSB first for each pixel, I have two way, to create a look up table or to write a function to do that (but will take time )

And finally on the button I am using, there is only bitmap command , no draw pixel, line, text, ... as you are using.

I have also the same button received as sample from NKK but step by step.


Again, thanks for your help.

Best Regards,
Youssef
